apiVersion: v1
kind: Service
metadata:
  name: sb-service
  namespace: app-be
  labels:
    run: sb-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
    name: http
  selector:
    run: sb-api