apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-nodejs
spec:
  capacity:
    storage: 400M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/nodejs"
  storageClassName: standard