apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-claim
  namespace: app-fe
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400M
  storageClassName: standard