apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: nginx-app
  labels:
    run: nginx-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30008
    name: https
  selector:
    run: nginx-app