apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-http-cm-test
  namespace: nginx-app
data:
  test.html: |
    <!doctype html>
    <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>Docker Nginx</title>
      </head>
      <body>
        <h2>This is the Test Page!</h2>
      </body>
    </html>